name: Build

on: workflow_call

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install
        run: npm ci
      - run: npm run lint
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install
        run: npm ci
      - run: npm run build
      - name: Upload app artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist